type: overfit
trainer: stage_inr
dataset:
  type: shapenet
  supervision: sdf  # sdf / occ / siren_sdf
  folder: /home/umaru/praktikum/changed_version/2023_visionpractical/data/1e9ef313876bfba7d02c6d35cc802839.obj.npy
  #folder: /home/umaru/PycharmProjects/meta_shaope/data/171shape_occ_sdf/val/1a6ad7a24bb89733f412783097373bdc.obj.npy
  #folder: /home/umaru/Downloads/happy_recon/happy_vrip_res4.xyz
  #1b0b1d2cb9f9d5c0575bd26acccafabd.obj.npy
  #1a04e3eab45ca15dd86060f189eb133.obj.npy
  transforms:
    type: shapenet

arch: # needs to add encoder, modulation type
  type: meta_low_rank_modulated_inr
  ema: null

  rank: [128] # list, assert len(n_weight_groups) in [1, hyponet.n_layer]
  modulated_layer_idxs: [0,1,2,3,4,5]
  use_factorization:  false

  n_inner_step: 5
  inner_lr: 0.003


  coord_sampler:
    data_type: image
    coord_range: [-1.0, 1.0]
    train_strategy: null
    val_strategy: null

  hyponet:
    share_bias: false  # normally false
    type: mlp
    n_layer: 6 # including the output layer
    hidden_dim: [256] # list, assert len(hidden_dim) in [1, n_layers-1]
    use_bias: true
    input_dim: 3
    output_dim: 2
    output_bias: 0.5  #0.5 ,0 for siren

    fourier_mapping:
      type: PE   # PE / Gaussian / siren equal None
      trainable: false
      use_ff: true  # has to be false when using siren
      ff_sigma: 0  # ff_dim = 2*ff_sigma *3 + (3)
      ff_dim: 3 # number of next channel / number of gaussians

    activation:
      type: relu  # siren
      siren_w0: null  #30 for siren

    initialization:
      weight_init_type: kaiming_uniform  #siren
      bias_init_type: zero  # zero/siren

    normalize_weight: true

loss:
  type: mse #now unnecessary
  subsample:
    type: null
    ratio: 0.1
  coord_noise: null

optimizer:
  type: adam            # overfit / adam
  init_lr: 0.001        # e1-4 for sirensdf  #5e-5 for sine   #1e-4 for bce loss
  weight_decay: 0.0000

  betas: [0.9, 0.95] #[0.9, 0.95]
  warmup:
    epoch: 0
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.001
    mode: adaptive
    step_size: 750
    gamma: 0.5
    patience: 30
    patience_adaptive: 30
    factor: 0.5
    threshold: 0
    start_from_zero: True
  max_gn: null

experiment:
  amp: True
  batch_size: 10
  total_batch_size: 10
  epochs: 20000
  epochs_cos: 30
  save_ckpt_freq: 2000
  test_freq: 30
  test_imlog_freq: 1000

