arch:
  type: low_rank_modulated_transinr
  ema: null
  data_encoder:
    type: PointNet2
    n_channel: 3
    trainable: false
    encoder_spec:
      patch_size: 9
      padding: 1
  latent_mapping:
    type: linear
    n_patches: 500
    n_layer: 1
    activation: relu
    hidden_dim:
    - 256
    latent_dim: 768
    use_pe: true
  transformer:
    n_layer: 6
    embed_dim: 360
    mask: false
    block:
      embed_dim: 360
      n_head: 12
      mlp_bias: true
      attn_bias: true
      attn_pdrop: 0.0
      resid_pdrop: 0.1
      gelu: v1
  hyponet:
    type: mlp
    n_layer: 5
    hidden_dim:
    - 256
    use_bias: true
    input_dim: 3
    output_dim: 2
    output_bias: 0.5
    fourier_mapping:
      type: PE
      trainable: false
      use_ff: true
      ff_sigma: 12
      ff_dim: 75
    activation:
      type: relu
      siren_w0: null
    initialization:
      weight_init_type: kaiming_uniform
      bias_init_type: zero
    normalize_weight: true
  coord_sampler:
    data_type: image
    coord_range:
    - -1.0
    - 1.0
    train_strategy: null
    val_strategy: null
  n_weight_groups:
  - 256
  modulated_layer_idxs:
  - 1
dataset:
  transforms:
    type: shapenet
  type: shapenet
  supervision: sdf
  folder: /home/umaru/PycharmProjects/meta_shaope/data/171shape_occ_sdf
optimizer:
  type: adam
  max_gn: null
  warmup:
    mode: adaptive
    start_from_zero: true
    epoch: 0
    multiplier: 1
    buffer_epoch: 0
    step_size: 1000
    min_lr: 0.0001
    patience_adaptive: 20000
    factor: 0.9
    threshold: 0
  init_lr: 0.0001
  weight_decay: 0.0
  betas:
  - 0.9
  - 0.999
  grad_accm_steps: 1
experiment:
  test_freq: 5000
  amp: true
  batch_size: 2
  total_batch_size: 2
  epochs_cos: 30
  epochs: 40000
  save_ckpt_freq: 50000
  test_imlog_freq: 250
loss:
  type: mse
  subsample:
    type: null
    ratio: 0.1
  coord_noise: coordwise
type: generalization
trainer: stage_inr
seed: 0
runtime:
  args:
    model_config: /home/umaru/praktikum/changed_version/2023_visionpractical/config/imagenette178_low_rank_modulated_transinr.yaml
    result_path: /home/umaru/praktikum/changed_version/2023_visionpractical/exp_week8
    task: ssdf_lr_1e-4
    load_path: ''
    postfix: ''
    seed: 0
    eval: false
    resume: false
    world_size: 1
    local_rank: 0
    node_rank: 0
    nnodes: 1
    nproc_per_node: 1
    dist_backend: nccl
    timeout: 1
    rank: 0
  extra_config: {}
  distenv:
    world_size: 1
    world_rank: 0
    local_rank: 0
    num_gpus: 1
    master: true
    device_name: NVIDIA GeForce RTX 3060 Laptop GPU
result_path: /home/umaru/praktikum/changed_version/2023_visionpractical/exp_week8/imagenette178_low_rank_modulated_transinr/ssdf_lr_1e-4
